[Etcd]
Servers = [
    "127.0.0.1:2379",
    "127.0.0.1:2381",
    "127.0.0.1:2383"
]

[Nsq]
Lookup = "127.0.0.1:4171"
Nsqd = "127.0.0.1:4154"

[Api]
[Api.Server]
    Addr = "0.0.0.0"
    Port = 7071
    Network = "tcp"
    Name = "im_api"
[Api.Client]
    Network = "tcp"
    Name = "im_api"

[Gateway]
[Gateway.Server]
    Addr = "0.0.0.0"
    Port = 7072
    Network = "tcp"
    Name = "im_Gateway"
[Gateway.Client]
    Network = "tcp"
    Name = "im_Gateway"

[GroupMessaging]
[GroupMessaging.Server]
    Addr = "0.0.0.0"
    Port = 7073
    Network = "tcp"
    Name = "im_group_messaging"
[GroupMessaging.Client]
    Network = "tcp"
    Name = "im_group_messaging"

[Messaging]
[Messaging.Server]
    Addr = "0.0.0.0"
    Port = 7074
    Network = "tcp"
    Name = "im_message_router"
[Messaging.Client]
    Network = "tcp"
    Name = "im_message_router"

[Dispatch]
[Dispatch.Server]
    Addr = "0.0.0.0"
    Port = 7075
    Network = "tcp"
    Name = "im_dispatch"
[Dispatch.Client]
    Network = "tcp"
    Name = "im_dispatch"


[Broker]
[Broker.Server]
    Addr = "0.0.0.0"
    Port = 7076
    Network = "tcp"
    Name = "im_group_broker"
[Broker.Client]
    Network = "tcp"
    Name = "im_group_broker"
