name: Publish & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: GoIM
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get Tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo go_im_${GITHUB_REF/refs\/tags\//}.tar.gz


      - name: Set Up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.16

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
            export CGO_ENABLED=0
            export GOOS=linux
            export GOARCH=amd64
            go build -o go_im ./cmd/run/singleton/

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          release_name: release_${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: build TAR PACKAGE
        run: tar -czvf go_im.tar.gz go_im

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.ref }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go_im.tar.gz
          asset_name: go_im_singleton_${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_content_type: application/gzip
