name: Publish & Deploy

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: GoIM
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get Tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo go_im_${GITHUB_REF/refs\/tags\//}.tar.gz


      - name: Set Up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.16

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          tag_name: ${{ github.hash }}
          release_name: release_${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: build TAR PACKAGE
        run: tar -czvf go_im.tar.gz ./dist/go_im

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GitAction }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go_im.tar.gz
          asset_name: go_im_${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_content_type: application/gzip

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/im_server
            wget https://github.com/dengzii/go_im/releases/latest/download/go_im_${{ steps.get_tag.outputs.TAG }}.tar.gz -O go_im_${{ steps.get_tag.outputs.TAG }}.tar.gz
            tar zxvf go_im_${{ steps.get_tag.outputs.TAG }}.tar.gz
            ./main